# Generated by Django 4.0.4 on 2022-04-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SAJoinList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('from_country', models.CharField(max_length=2)),
                ('to_country', models.CharField(max_length=2)),
                ('transfer_amount', models.PositiveIntegerField()),
                ('sell_amount', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Join list',
                'db_table': 'sa_join_list',
            },
        ),
    ]
